### ISSUE TITLE
[BUG] Horizontal scroll

### ISSUE THREAD

**Issue by jagnani73** [prakharrathi25/prakharrathi25-portfolio#1]
There is an unneeded horizontal scroll
![image](https://user-images.githubusercontent.com/60016972/135522492-991c0087-529d-4df9-a837-e160ba5cd108.png)

**Comment by jagnani73** [comment]
@prakharrathi25 I would like to work on this issue!

**Comment by prakharrathi25** [comment]
Sounds like a great idea! Thanks!
